env: APP_ENV="travis"

language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
  - php: 5.3
  - php: hhvm
  - php: 7

addons:
  hosts:
    - dev.patrickascher.at

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y beanstalkd
  - sudo sed -i 's/#START=yes/START=yes/' /etc/default/beanstalkd
  - sudo service beanstalkd start
  - git clone git://github.com/phalcon/cphalcon.git $TRAVIS_BUILD_DIR/vendor/cphalcon
  - cd $TRAVIS_BUILD_DIR/vendor/cphalcon/build && ./install && cd $TRAVIS_BUILD_DIR
  - echo 'extension=phalcon.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -e "create database IF NOT EXISTS auth;" -uroot
  - mysql -uroot auth < schemas/auth_2015-10-10.sql
  - mysql -e "USE mysql;UPDATE user SET password=PASSWORD('root') WHERE user='root';FLUSH PRIVILEGES;"
  - composer self-update
  - composer require satooshi/php-coveralls:~0.6@stable
  - composer install

script:
  - mkdir -p build/logs
  - php build/puppet/modules/php/files/phpunit-4.6.0.phar --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
